### PR TITLE
Amend error messages for editModuleCommand

### LINKED ISSUE #187: [PE-D] Returns invalid command for a valid command
If edit module is not in the list, it returns a "INVALID COMMAND" even though it is a valid command

If remove module is not in the list, it returns a "INVALID COMMAND" even though it is a valid command

Perhaps you can change the error message to "module not in list" instead of "INVALID COMMAND"

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: chuhann/ped#2

### LINKED ISSUE #212: [PE-D] Better error messages for Edit
Should have better error messages to identify what is wrong with the command. For example "invalid module" or "module not entered before" instead of invalid command. Can also specify what is the correct format for edit?

Same for remove

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Speedweener/ped#3

### PR DESCRIPTION
**Pull request by harryleecp**
Fixes #187 and fixes #212

### CODE REVIEW

File: src/main/java/seedu/duke/apps/academicplanner/commands/EditModuleCommand.java [hunk 1]
```diff
@@ -15,7 +15,8 @@
 public class EditModuleCommand extends Command {
     private static final String EDIT_SEMESTER = "1";
     private static final String EDIT_GRADE = "2";
-    private static final String ERROR_INVALID_COMMAND = "INVALID COMMAND";
+    //private static final String ERROR_INVALID_COMMAND = "INVALID COMMAND";
```
Comment (jerroldlam) [inline src/main/java/seedu/duke/apps/academicplanner/commands/EditModuleCommand.java:18]: Can remove this commented out line
